// Type-only re-export of the bundle's surface.
//
// The bundle (_validator.bundle.js) is generated by scripts/bundle-validator.ts
// and gitignored. It's a single esbuild output covering @bids/validator's
// library API. TypeScript needs to know what the bundle exports for
// `await import('./_validator.bundle.js')` to type-check, so we mirror
// the shim's surface here -- the shim is the authoritative type source
// (hand-written), the bundle is just its esbuild-compiled runtime.

export * from './_validatorEntry'
