// Compact runtime summary derived from `translations.lock.json`. We
// don't ship the lock file at runtime — it's pure tooling metadata,
// and at ~170 KB the renderer bundle has no reason to carry it. The
// summary file is a few bytes and tracks one boolean per non-English
// locale: "does this catalog still have entries that no native speaker
// has confirmed?". The Preferences pane's "translations marked for
// review" hint keys off it. See i18n design history in git log §"Decision log" #5.
//
// The summary is regenerated by `scripts/translate-i18n.ts` whenever
// the lock file is rewritten, and `scripts/check-i18n.ts` enforces
// that the summary matches the lock file's computed truth (so a hand-
// edit of the lock that flips a `humanReviewed: true` without
// regenerating the summary fails CI).

import type { SupportedLocale } from './locales'
import summary from './locales/review-summary.json'

interface ReviewSummary {
  schemaVersion: number
  unreviewedByLocale: Partial<Record<SupportedLocale, boolean>>
}

const UNREVIEWED_BY_LOCALE = (summary as ReviewSummary).unreviewedByLocale

/**
 * Returns true if the named locale's catalog still has entries that
 * have not been reviewed by a native speaker. English is always false
 * (it's the source of truth). The Preferences pane uses this to surface
 * a small "(translations marked for review)" hint so beta testers know
 * the chrome they see is provisional.
 */
export function hasUnreviewedTranslations(locale: SupportedLocale): boolean {
  if (locale === 'en') return false
  return UNREVIEWED_BY_LOCALE[locale] === true
}
