#!/usr/bin/env python3
"""pet2bids_prototype.py — end-to-end PET DICOM -> validated BIDS-PET project.

Reference oracle for the BIDSvue M12 PET importer. Run an input DICOM folder
through pypet2bids' Dcm2niix4PET, lay the result into a minimal BIDS project,
and optionally run bids-validator. See README.md for usage.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

from pypet2bids.dcm2niix4pet import Dcm2niix4PET


# Where pypet2bids should find dcm2niix. We always pass an explicit path so
# we get the dev build, not whatever happens to be bundled with the package.
def discover_dcm2niix() -> Path:
    found = shutil.which("dcm2niix")
    if found is None:
        sys.exit(
            "ERROR: dcm2niix not found on PATH. Add a recent dcm2niix build "
            "to PATH or symlink the binary."
        )
    return Path(found)


def load_metadata(path: Path | None) -> dict[str, Any]:
    """Load an operator-supplied PET metadata JSON.

    The file is a flat JSON object whose keys are BIDS-PET sidecar fields
    (TracerName, InjectedRadioactivity, ModeOfAdministration, TimeZero, ...).
    Values are passed through to pypet2bids' additional_arguments, which
    overlay onto whatever dcm2niix + the pypet2bids enrichment derived from
    DICOM. Operator wins on conflict.
    """
    if path is None:
        return {}
    with path.open() as f:
        data = json.load(f)
    if not isinstance(data, dict):
        sys.exit(f"ERROR: metadata file {path} must contain a JSON object.")
    return data


def write_bids_scaffolding(root: Path, dataset_name: str) -> None:
    """Write the minimum top-level files bids-validator requires."""
    root.mkdir(parents=True, exist_ok=True)

    description = {
        "Name": dataset_name,
        "BIDSVersion": "1.10.0",
        "DatasetType": "raw",
        "Authors": ["BIDSvue M12 pet2bids-prototype"],
        "GeneratedBy": [
            {
                "Name": "pet2bids-prototype",
                "Description": "BIDSvue M12 reference oracle wrapping pypet2bids.",
            }
        ],
    }
    (root / "dataset_description.json").write_text(
        json.dumps(description, indent=2) + "\n"
    )
    (root / "README").write_text(
        f"# {dataset_name}\n\n"
        "Test dataset generated by the BIDSvue M12 PET importer reference\n"
        "oracle (pet2bids-prototype). The prototype wraps pypet2bids' end-\n"
        "to-end pipeline (dcm2niix conversion + PET-specific JSON sidecar\n"
        "enrichment from operator-supplied metadata) and lays the output\n"
        "into a minimal valid BIDS-PET project.\n\n"
        "This dataset is intended as a smoke test, not as research data.\n"
        f"The source DICOM series is a single PET acquisition ({dataset_name}).\n"
    )


def run_dcm2niix4pet(
    image_folder: Path,
    destination: Path,
    metadata: dict[str, Any],
    dcm2niix_path: Path,
    tracer: str | None,
) -> None:
    """Drive pypet2bids' Dcm2niix4PET class directly.

    destination is the per-subject PET directory, e.g.
    <bids_root>/sub-<label>/pet/. Dcm2niix4PET names output files from the
    final two segments of destination_path, so passing sub-<label>/pet
    yields sub-<label>_pet.{nii.gz,json}.
    """
    destination.mkdir(parents=True, exist_ok=True)

    # Write the dcm2niix path into ~/.pet2bidsconfig so Dcm2niix4PET picks it
    # up via its existing config-file path. Mirrors what `dcm2niix4pet
    # --set-dcm2niix-path` does on the CLI.
    config_path = Path.home() / ".pet2bidsconfig"
    config_lines = []
    if config_path.exists():
        for line in config_path.read_text().splitlines():
            if not line.startswith("DCM2NIIX_PATH"):
                config_lines.append(line)
    config_lines.append(f"DCM2NIIX_PATH={dcm2niix_path}")
    config_path.write_text("\n".join(config_lines) + "\n")

    kwargs: dict[str, Any] = dict(metadata)
    if tracer:
        kwargs.setdefault("TracerName", tracer)

    converter = Dcm2niix4PET(
        image_folder=str(image_folder),
        destination_path=str(destination),
        additional_arguments=kwargs,
        silent=False,
    )
    converter.run_dcm2niix()


def validate(root: Path) -> int:
    """Run bids-validator against the BIDS root."""
    print(f"\n=== bids-validator: {root} ===")
    cmd = ["bids-validator", str(root)]
    print(f"$ {' '.join(cmd)}")
    proc = subprocess.run(cmd)
    return proc.returncode


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Wrap pypet2bids end-to-end to convert one PET DICOM series into a "
            "validated BIDS-PET dataset."
        )
    )
    parser.add_argument(
        "--input",
        required=True,
        type=Path,
        help="Source DICOM directory (single series).",
    )
    parser.add_argument(
        "--subject",
        required=True,
        help="BIDS subject label without the 'sub-' prefix.",
    )
    parser.add_argument(
        "--session",
        default=None,
        help="Optional BIDS session label without the 'ses-' prefix.",
    )
    parser.add_argument(
        "--metadata",
        type=Path,
        default=None,
        help="Optional operator-supplied JSON of BIDS-PET sidecar fields.",
    )
    parser.add_argument(
        "--tracer",
        default=None,
        help="Optional PET tracer name (e.g. FDG). Stored as TracerName.",
    )
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Destination BIDS dataset root.",
    )
    parser.add_argument(
        "--validate",
        action="store_true",
        help="Run bids-validator against the resulting dataset.",
    )
    args = parser.parse_args()

    if not args.input.is_dir():
        sys.exit(f"ERROR: --input {args.input} is not a directory.")

    dcm2niix_path = discover_dcm2niix()
    print(f"Using dcm2niix at {dcm2niix_path}")

    metadata = load_metadata(args.metadata)
    if metadata:
        print(
            f"Loaded {len(metadata)} metadata fields from {args.metadata}: "
            f"{sorted(metadata)}"
        )

    bids_root = args.output.resolve()
    write_bids_scaffolding(bids_root, dataset_name=args.subject)

    subject_segment = f"sub-{args.subject}"
    if args.session:
        session_segment = f"ses-{args.session}"
        pet_dir = bids_root / subject_segment / session_segment / "pet"
    else:
        pet_dir = bids_root / subject_segment / "pet"

    run_dcm2niix4pet(
        image_folder=args.input.resolve(),
        destination=pet_dir,
        metadata=metadata,
        dcm2niix_path=dcm2niix_path,
        tracer=args.tracer,
    )

    print(f"\nBIDS project written to {bids_root}")
    for f in sorted(pet_dir.glob("*")):
        print(f"  {f.relative_to(bids_root)}")

    if args.validate:
        rc = validate(bids_root)
        if rc != 0:
            print(f"\nbids-validator exited {rc}", file=sys.stderr)
            return rc
        print("\nbids-validator passed.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
