#!/usr/bin/env bun
/**
 * Synthetic-dataset scanner benchmark. Generates a BIDS-shaped tree of
 * `BENCH_FILES` files (default 50000 -- the M2 acceptance target; set
 * BENCH_FILES=100000 for the spec §3.3 trigger measurement), runs the
 * scanner over it via the node:fs adapter, reports timing and resident
 * memory, and optionally checks the result against a committed baseline
 * so CI can gate on perf regressions.
 *
 * Modes:
 *   bun run scripts/bench-scanner.ts              # baseline mode: run + write trend file
 *   BENCH_FILES=100000 bun run …                  # run at a different size
 *   BENCH_KEEP=1 bun run …                        # keep the temp dataset
 *   BENCH_CHECK=1 bun run …                       # compare against the baseline; exit 1 on regression
 *   BENCH_SAVE_BASELINE=1 bun run …               # overwrite the baseline with this run's result
 *
 * Baseline lives at bench/baselines/scanner.json and is checked into the
 * repo. Per-run trend results land at bench/results/scanner-<ts>.json
 * (gitignored). CI runs with BENCH_CHECK=1.
 */

import {
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  rm,
  writeFile,
} from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { performance } from 'node:perf_hooks'
import { type FileSystemAdapter, scanDataset } from '../src/lib/bids/scanner'

const TARGET_FILES = Number(process.env.BENCH_FILES ?? '50000')
const KEEP = process.env.BENCH_KEEP === '1'
const CHECK_AGAINST_BASELINE = process.env.BENCH_CHECK === '1'
const SAVE_BASELINE = process.env.BENCH_SAVE_BASELINE === '1'

/**
 * How much slower than the baseline counts as a regression. Generous on
 * purpose: GitHub Actions runners are slower than typical dev machines and
 * the runtime varies between runs. The gate catches major regressions
 * (e.g. an algorithmic change that takes 2x longer) without false-firing
 * on incidental noise.
 *
 * Empirically Ubuntu CI runners have shown ~2x scan-time spread across
 * runs on identical code (968-1305 ms typical, but a 2002 ms outlier was
 * observed on commit e7a0246 with no scanner-touching changes), so the
 * threshold sits at 2.5x to absorb that variance with a margin. If this
 * trips on real noise again, the next iteration is multi-sampling within
 * a single run and taking the median rather than ratcheting this further.
 */
const REGRESSION_THRESHOLD = 2.5

const BASELINE_PATH = 'bench/baselines/scanner.json'

const nodeFs: FileSystemAdapter = {
  async readDir(path) {
    const entries = await readdir(path, { withFileTypes: true })
    return entries.map((e) => ({
      name: e.name,
      isDirectory: e.isDirectory(),
      isFile: e.isFile(),
      isSymlink: e.isSymbolicLink(),
    }))
  },
  async readTextFile(path) {
    return readFile(path, 'utf8')
  },
}

interface Plan {
  root: string
  subjects: number
  sessions: number
  datatypes: string[]
  filesPerDatatype: number
  totalFiles: number
}

function planLayout(targetFiles: number): Omit<Plan, 'root'> {
  // Aim for roughly subjects:sessions:datatypes:files-per-datatype near
  // 50:5:4:100 = 100k. Scale down for smaller targets.
  const datatypes = ['anat', 'func', 'fmap', 'dwi']
  const filesPerDatatype = 50
  const sessions = 2
  const cells = datatypes.length * sessions * filesPerDatatype
  const subjects = Math.max(2, Math.ceil(targetFiles / cells))
  const totalFiles = subjects * sessions * datatypes.length * filesPerDatatype
  return { subjects, sessions, datatypes, filesPerDatatype, totalFiles }
}

async function generateDataset(plan: Plan): Promise<void> {
  // dataset_description.json + dataset_description-shaped scaffold so the
  // scanner accepts the root.
  await writeFile(
    join(plan.root, 'dataset_description.json'),
    JSON.stringify({ Name: 'bench', BIDSVersion: '1.8.0' }, null, 2),
  )
  await writeFile(
    join(plan.root, 'README'),
    'Synthetic benchmark dataset — generated by scripts/bench-scanner.ts.\n',
  )

  for (let s = 0; s < plan.subjects; s++) {
    const sub = `sub-${String(s + 1).padStart(3, '0')}`
    for (let ss = 0; ss < plan.sessions; ss++) {
      const ses = `ses-${String(ss + 1).padStart(2, '0')}`
      for (const datatype of plan.datatypes) {
        const dir = join(plan.root, sub, ses, datatype)
        await mkdir(dir, { recursive: true })
        for (let f = 0; f < plan.filesPerDatatype; f++) {
          const stem = `${sub}_${ses}_acq-bench_run-${String(f + 1).padStart(2, '0')}_${suffixFor(datatype)}`
          // Empty files are fine — the scanner doesn't read them.
          await writeFile(join(dir, `${stem}.nii.gz`), '')
          if (f % 2 === 0) {
            // Half the files have sidecars, to exercise pairing.
            await writeFile(
              join(dir, `${stem}.json`),
              JSON.stringify({ EchoTime: 0.03 }, null, 2),
            )
          }
        }
      }
    }
  }
}

function suffixFor(datatype: string): string {
  switch (datatype) {
    case 'anat':
      return 'T1w'
    case 'func':
      return 'bold'
    case 'fmap':
      return 'magnitude1'
    case 'dwi':
      return 'dwi'
    default:
      return 'unknown'
  }
}

interface BenchSummary {
  timestamp: string
  targetFiles: number
  actualFiles: number
  layout: Omit<Plan, 'root'>
  generationMs: number
  scanMs: number
  heapDeltaMB: number
  heapAfterMB: number
  bidsIgnorePatterns: number
  indexedNodes: number
}

interface Baseline {
  /** Notes about where this baseline was captured (machine / commit / etc.). */
  capturedOn: string
  capturedAt: string
  targetFiles: number
  scanMs: number
  heapDeltaMB: number
  indexedNodes: number
}

async function loadBaseline(): Promise<Baseline | null> {
  try {
    const text = await readFile(BASELINE_PATH, 'utf8')
    return JSON.parse(text) as Baseline
  } catch {
    return null
  }
}

async function main(): Promise<void> {
  const layout = planLayout(TARGET_FILES)
  const root = await mkdtemp(join(tmpdir(), 'bidsvue-bench-'))
  console.log(
    `Plan: ${layout.subjects} subjects × ${layout.sessions} sessions × ${layout.datatypes.length} datatypes × ${layout.filesPerDatatype} files = ${layout.totalFiles} files at ${root}`,
  )

  const generationStart = performance.now()
  await generateDataset({ root, ...layout })
  const generationMs = performance.now() - generationStart
  console.log(`Generated in ${formatMs(generationMs)}.`)

  const heapBefore = process.memoryUsage().heapUsed
  const scanStart = performance.now()
  const result = await scanDataset(root, { fs: nodeFs })
  const scanMs = performance.now() - scanStart
  const heapAfter = process.memoryUsage().heapUsed

  if (!result.ok) {
    console.error('Scan failed:', result.error)
    process.exit(1)
  }

  const summary: BenchSummary = {
    timestamp: new Date().toISOString(),
    targetFiles: TARGET_FILES,
    actualFiles: layout.totalFiles,
    layout,
    generationMs,
    scanMs,
    heapDeltaMB: (heapAfter - heapBefore) / 1024 / 1024,
    heapAfterMB: heapAfter / 1024 / 1024,
    bidsIgnorePatterns: result.dataset.bidsIgnorePatterns.length,
    indexedNodes: result.dataset.index.byPath.size,
  }

  console.log()
  console.log(`Scan: ${formatMs(scanMs)}`)
  console.log(`Heap delta: ${summary.heapDeltaMB.toFixed(1)} MB`)
  console.log(`Heap after: ${summary.heapAfterMB.toFixed(1)} MB`)
  console.log(`Indexed nodes: ${summary.indexedNodes}`)

  await mkdir('bench/results', { recursive: true })
  const outPath = `bench/results/scanner-${summary.timestamp.replace(/[:.]/g, '-')}.json`
  await writeFile(outPath, `${JSON.stringify(summary, null, 2)}\n`)
  console.log(`Wrote ${outPath}`)

  if (!KEEP) {
    await rm(root, { recursive: true, force: true })
  } else {
    console.log(`Keeping ${root} (BENCH_KEEP=1)`)
  }

  if (SAVE_BASELINE) {
    const baseline: Baseline = {
      capturedOn: process.platform,
      capturedAt: summary.timestamp,
      targetFiles: summary.targetFiles,
      scanMs: summary.scanMs,
      heapDeltaMB: summary.heapDeltaMB,
      indexedNodes: summary.indexedNodes,
    }
    await mkdir('bench/baselines', { recursive: true })
    await writeFile(BASELINE_PATH, `${JSON.stringify(baseline, null, 2)}\n`)
    console.log()
    console.log(`Wrote baseline ${BASELINE_PATH}`)
  }

  if (CHECK_AGAINST_BASELINE) {
    const baseline = await loadBaseline()
    if (baseline === null) {
      console.error(
        `\nBENCH_CHECK=1 but no baseline at ${BASELINE_PATH}. Run with BENCH_SAVE_BASELINE=1 first.`,
      )
      process.exit(1)
    }
    if (baseline.targetFiles !== summary.targetFiles) {
      console.error(
        `\nBaseline targetFiles=${baseline.targetFiles} but this run was ${summary.targetFiles}. Mismatched runs aren't comparable.`,
      )
      process.exit(1)
    }
    const ratio = summary.scanMs / baseline.scanMs
    console.log()
    console.log(
      `Baseline scan: ${formatMs(baseline.scanMs)} (captured on ${baseline.capturedOn})`,
    )
    console.log(
      `Ratio: ${ratio.toFixed(2)}× baseline (gate fails at ${REGRESSION_THRESHOLD.toFixed(2)}×)`,
    )
    if (ratio > REGRESSION_THRESHOLD) {
      console.error(
        `\nRegression: this run took ${(ratio * 100).toFixed(0)}% of baseline (> ${(REGRESSION_THRESHOLD * 100).toFixed(0)}%).`,
      )
      process.exit(1)
    }
    console.log('Within budget.')
  }
}

function formatMs(ms: number): string {
  return ms < 1000 ? `${ms.toFixed(0)} ms` : `${(ms / 1000).toFixed(2)} s`
}

await main()
